umi_tools/extract.py
=> Use iterator to reduce memory usage in paired end processessing

umi_tools/dedup.py
=> Is 2pass pairing

umi_tools/dedup.py
=> Compatibility with python3

QUICK_START.md
great documentation, appreciate the level of detail!
=> typo corrections to QUICK_START.md

umi_tools/group.py
=> debugs group command with paired end input and bam output

umi_tools/extract.py
Trivial mods for monitoring the progress of the extract method.
I believe if not present in other commands should/can be added.
=> {ts} support cell barcodes

.travis.yml, doc/INSTALL.rst, doc/Single_cell_tutorial.md, test_umi_tools.sh
Adds OS X testing to travis
The purpose is to test installation on OS X. Therefore travis testing only includes installation and then running each tool with `--help`
=> {ts} add osx travis

umi_tools/umi_methods.py
get_read_position will now use the position of the FIRST splice junction in the read (in reference coords) in the key if spliced-is-unique is set instead of just true or false.
=> Use splice position in read key

doc/Single_cell_tutorial.md
Fix a few misspellings in Single_cell_tutorial.md.
=> Fix spelling in docs

umi_tools/umi_methods.py
In the process of trying to work out what's going on in #220, I realised that the quality strings for read2 are not correct! I thought I'd dealt with this in #201 but it appears I only sorted out the read sequence.
=> debugs extraction with string barcodes patterns

umi_tools/count.py
@romanhaa is getting an error due to the memory requirements to pivot a dataframe in `pandas` (#219). Use of `pandas` is overkill here so I've refactored to just use a simple `dict`
=> refactoring writing out count data to reduce memory req.

umi_tools/Utilities.py
=> debugs --skip-tags-regex option

setup.py, umi_tools/umi_tools.py
Directly import `__version__` from package where needed rather than modifying `sys.path` and importing from `version.py`
=> {ts} update version import

umi_tools/Utilities.py
See #278. Don't merge until py2 tests issue is resolved
=> adds check for tag options

umi_tools/whitelist.py
Also added the command-line name to the error messages.
=> Use correct option's name for --bc-pattern2

umi_tools/__init__.py, umi_tools/network.py
remember to export UMIClusterer from root namespace.
=> export UMIClusterer from root namespace

umi_tools/sam_methods.py
attempt to fix #337  by changing `&` to `and`.
=> attempt to fix #337

doc/regex.md
Added two example sections:
* Example: extracting UMIs
* Example: extracting barcodes and UMIs
These have example regexes and FASTQ fragements and show
how the regexes match the FASTQ reads and the output FASTQ
files that would be produced.
=> Extended regex.md 'Regex (regular expression) mode' with examples

umi_tools/extract_methods.py
This introduces a check that barcode strings do not contain non-NCX characters
See #393 for motivation.
=> adds checks that barcode string contains only NCX characters

umi_tools/dedup.py, umi_tools/group.py
Explanation of stats files was insufficient
See #395 for motivation.
=> updates documenation for stats option

umi_tools/Utilities.py, umi_tools/extract_methods.py, umi_tools/whitelist.py
I updated by umi_tools devel env to python 3.8 and its new syntax checker picked up a bunch of errors waiting to happen...
=> Errors picked up by python 3.8's syntax checker

umi_tools/extract.py
=> Insert missing "options" in test for white list conditions

umi_tools/extract.py
Fixed missing % in error message
=> Fixing syntax warning in extract.py

umi_tools/umi_methods.py
Found this old branch hanging around that hopefully fixes #580, hopefully.
=> {is} fix read suffix line end

umi_tools/dedup.py
=> Resolves pandas aggregation warnings
