- umi_tools/dedup.py
@IanSudbery After discussing with @MikeDMorgan I've implemented a two-stage random sampling since the original array of probabilities contains the same probability multiple times (e.g 1/n, 2/n, 3/n, ..., where n is the total umi counts) This speeds up the random sampling ~5-fold for the BAM from Roy Francis (see below) so the total run time decreased from ~28 minutes to ~10 minutes. This may be a particular case where the gains are larger since the distribution of UMIs is a long way off uniform. I'd expect the improvement to be marginal where the distribution of umis is more "random".
I've checked the stats output is consistent. 
Can you think of any scenario where this method of sampling would be significantly less efficient?
previously...
ncalls  tottime  percall  cumtime  percall …
> Ts speed up stats

- README.rst
It's always a good idea to prefix shell commands with the universal prompt character `$`
> README.rst: Prefix shell commands with `$'

- umi_tools/dedup.py
Paired writer was calling fetch on outfile rather than infile to find unmatched pairs cf issue #50.
Can't think what I was thinking when I wrote this. Clearly the first person to run a paired file that had paired reads in it (or mates on a different chromosome) was going to trigger this error.
> outfile.fetch in paired output writer. 

- ez_setup.py
- setup.py
@IanSudbery I've hardcoded a minimum requirement for setuptools in the use_setuptools() function. previously we didn't specify a minimum version so it defaults to the latest version. 
I think this is the most likely explanation for the odd installation errors where it appears to reinstall setuptools even after installing all the requirements. This was stopping the conda build working for me. However, this also suggests the easy install solution might not work when required?
> Tom smith cgat patch setuptools

- umi_tools/dedup.py
- umi_tools/group.py
- umi_tools/network.py
- umi_tools/umi_methods.py
This contains most of the changes implemented to improved run-time. See #69 for a full discussion of the changes. 
The recursive search was causing test failure due to changes in output order for the _group_cluster_ test. On further inspection, the output from _dedup_ when run on a high depth BAM is also not consistent between the `breath_first_search` and `breath_first_search_recursive` functions. 
@IanSudbery I can't see why the recursive search should modify the output but I'll try and look into this shortly. For the time being, the recursive search has been commented out.
> Ts replace comprehension

- umi_tools/umi_methods.py
There is currently a bug with tid not actually fetching just the chromosome of interest in pysam.  This slows down the deduping for files with large amounts of contigs.  At least on my computer if you fetch via tid, all the reads get fetched (issue https://github.com/pysam-developers/pysam/issues/415).  While we wait for that bug to get fixed, I fixed this issue by removing tids from the code using the chromosome name instead.
This fixes issue https://github.com/CGATOxford/UMI-tools/issues/93 that I created.
Is there any testing or QC you'd like to me run before accepting this, let me know, I haven't done anything yet.
> Speed up paired end umi deduping

- umi_tools/umi_methods.py
pysam.AlignedSegment.next_reference_name throws ValueError if the mate is unmapped.
If `group` is run with `--output-unmapped` then if read1 is mapped, but read2 is not, TwoPassWriter throws an error because of this. 
This fix skips trying to store the mate details for delayed outputting if the mate is unmapped. In this case the mate is output independently anyway.
> Do not cache read for mate output if mate is unmapped.

- umi_tools/Utilities.py
Python3 requires an encoding and text mode to be specified to be able to output strings to a zip file. This was breaking the ability output to a zip file from extract if the user was using python 3.X.
This should really have tests, but I don't have time to implement right now.
> py3 transparent gzipped output

- umi_tools/dedup.py
- umi_tools/umi_methods.py
The --gene-tag option previously assumed all gene tags were gene names. featureCounts and HTSeq both use the same tag for the gene as the assignment status. These commits introduces the --gene-tags-skip option to ensure unassigned reads do not cause bundles to be yielded prematurely and unassigned reads are not outputted.
> {ts} debug per gene

- QUICK_START.md
From the context of Step5 Deduplication, in deduplicated_edit_distance.tsv file's third line, the positions where the average edit distance between UMIs is 1 should be '1167', not '11167'.
> Update deduplicated_edit_distance.tsv's description

- umi_tools/umi_tools.py
umi_tools crashes when running on a system without a graphical interface.
```  File "python3.6/tkinter/__init__.py", line 2017, in __init__
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```
small fix that worked on my cluster
> added import at start of umi_tools

- MANIFEST.in
- tests/test_style.py
- umi_tools/count.py
- umi_tools/count_tab.py
- umi_tools/dedup.py
- umi_tools/extract.py
- umi_tools/group.py
- umi_tools/network.py
- umi_tools/umi_methods.py
- umi_tools/umi_tools.py
- umi_tools/whitelist.py
Removes try except statements from around the import statements. 
I think these were neccessary because previously if you imported ran in a local directory that contained an `umi_tools` package, it would try to load from there and then get confused, which messed with the tests. This is fixed by adding `from __future__ import absolute_import`
also moved `matplotlib` backend specification to umi_methods.py from `umi_tools.py`
> {is} remove tryexcept

- tests/tests.yaml
- umi_tools/Utilities.py
- umi_tools/count.py
- umi_tools/count_tab.py
- umi_tools/dedup.py
- umi_tools/extract.py
- umi_tools/group.py
- umi_tools/umi_methods.py
- umi_tools/whitelist.py
Introduces the `--expect-cells` option for `whitelist` - as per the [CellRanger pipeline](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/count)
This is a half way house between full automation and the user defining the exact number of cells present. Should allow the user obtain an automatic estimate of the number of true cell barcodes with some prior information about the upper limit on how many cells have been sequenced. Use of this options assumes the user has at least a reasonable estimate of the number of cells as discussed [here](https://assets.contentful.com/an68im79xiti/57MmukfLzqI4WMeyKQMqom/557f2d3119e7cd7bb819a22b28118925/CG000091_10x_Technical_Note_Guidelines_on_Accurate_Target_Cell_Count.pdf) and that the capture rate exceeds 10% …
> {ts} add expect cells option

- umi_tools/dedup.py
- umi_tools/umi_methods.py
Resolves (#190) as far as I can tell. Have confirmed that `dedup` previously errored with non-informative message when input BAM containing no reads. This is no longer the case. If there are no positions for de-duplication, this is now raised as a warning in the logfile but exit status is 0.
> {ts} debug no positions

- umi_tools/Utilities.py
The naming of this option causes confusions since the introduction (by me) of very similar sounding `--per-contig` option. E.g see #185. Hopefully, the renaming will resolve this confusion
> renames --whole-contig option to --buffer-whole-contig and updates doc.

- umi_tools/extract.py
- umi_tools/umi_methods.py
Multiple debugs for use of  `--bc-pattern`. The most worrying is that when using `--bc-pattern` and `--bc-pattern2`, the number of bases removed from read2 = len(pattern) not len(pattern2)! (9354d2660425eea58e459b17ffbb834ab7c45455) This is obviously not a problem when pattern and pattern2 are the same length, as is frequently the case, but the user will be unaware of this issue, unless pattern2 is longer than pattern in which case an error will be thrown.
> {ts} debug bc pattern2

- doc/Single_cell_tutorial.md
- umi_tools/Utilities.py
Rectifies error in documentation identified by @hy09 (#211).
Note - fuzzy matching is covered in the testing and the regex provided defines the fuzzy match incorrectly. This should also be updated in due course in case any one ever looks at the testing to help them define their regex (unlikely but possible I guess)
> Tom smith cgat fuzzy doc patch

- umi_tools/extract.py
- umi_tools/umi_methods.py
@IanSudbery  - This branch introduces an experimental option `--retain-umi` in `extract` to retain the umi in the read sequence. 
I used this for some (slightly unusual) samples where ~2/3 of reads contain a 1-9bp sequence of non-template nucleotides which are added to the 5' end of the read prior to amplification. This is not by design! However, the benefit is that the first 9bp can be used as a pseudo-umi but the length and presence of the non-tempate nucleotides is not consistent so I also need to retain the pseudo-umi in the read sequence and allow the aligner to soft-clip where appropriate. The other option would have been to extract the soft-clipped bases from the BAM and annotate the BAM with these. However, this wouldn't have worked with `umi_tools dedup` due to the need for a …
> {ts} add retain umi option

- umi_tools/count.py
Does what is says on the tin. I introduced this bug in the simplification of `count` output. This wasn't picked up in the test since the test input only has two cells.
> debugs wide-format counts output for #227

- doc/QUICK_START.md
Read: TAGCCGGCTTTGCCCAATTGCCAAATTTTGGGGCCCCTATGAGCTAG 
Barcode: NNNXXXXNN
Thus processed read should be CCGGTTGCCCAATTGCCAAATTTTGGGGCCCCTATGAGCTAG. There was a base missing at the end of the sequence.
> Fixed "processed read" diagram in QUICK_START.md

- README.rst
This also increases interoperability with other tools.
> Suggest installation via bioconda instead of custom channel.

- umi_tools/__init__.py
Having a `umi_tools.__version__` string
is the standard recommended Python way
to make the version number accessible.
This commit does that.
> added `__version__`

- umi_tools/network.py
I realised that currently the `iter_nearest_neighbours` function, which is used for umi bundles > 25, produces pairs similar to those produced by `it.permutations`, i.e. (B, A) as well as (A, B), whereas for umi_bundles < 25, `it.combinations` is used (producing just (A, B)). This change would make the `iter_nearest_neighbours` function also produce combinations. I don't know whether this bug had any difference on the output, but even if not I think it should reduce the number of pairwise edit distances that have to be computed even further (by exactly half, I'm guessing...?)
> Alter iter_nearest_neighbours to produce combinations not permutations

- .travis.yml
Matplotlib >= 3.0 doesn't support py2. Causes fail:
https://travis-ci.org/CGATOxford/UMI-tools/jobs/433394475#L586-L600
Switching to hardcoding 2.2.3 whilst we maintain py2 support ourselves.
> Debug py2 test fails

- umi_tools/count.py
- umi_tools/count_tab.py
- umi_tools/group.py
- umi_tools/network.py
- umi_tools/sam_methods.py
Call signature for `UMIClusterer` was `__call__(umis, counts, threshold=1)`  where `umis` was a list of UMIs and `counts` was a dictionary mapping UMIs to their counts. This seemed unnecesssary as `umis` could be recovered from `counts` with `counts.keys()`. When I wrote the API website page, I pretended it wasn't there. This pull makes the reality match the docs.
Also fixes pysam<0.14 errors if tag is missing.
> Refactored UMIClusterer to remove unncessesary arguement to __call__

- umi_tools/sam_methods.py
Due to the feedback from @IanSudbery, I have now just created a pull request for the trivial and easy fix for having multiple identical read1 alignments in the case the read2 alignment is missing by extending one condition.
Best,
Christian
> Fix for incorrect output of dedup with --paired (#347) in case of duplicated lines

- umi_tools/dedup.py
A user queried the use of quality in which read is kept upon
deduplication (#261)
> your selection procedure does not seem to take into
> account read sequencing quality (only mapping quality).
>
> In other words, if 2 reads have the same high score
> mapping quality (i.e. unique mappers), one being long and
> with good base scores, the other short with errors, it will
> select randomly among these, too, right?
The response was:
> Yes, that's correct.
Updated umi-tools/dedup.py "Selecting the representative read" comment
section to clarify that the read quality is not used.
> Clarified Selecting the representative read documentation

- .travis.yml
- umi_tools/dedup.py
- umi_tools/group.py
After a bit of digging, the source of the travis fails has been identified as `samtools` v1.10 (https://github.com/samtools/samtools/releases/tag/1.10) which now adds a header line to the output sam, containing the sort command itself. I took the easy route out and added the `--no-PG` to our `samtools sort` call. If we think that users may actually want to have this line included in the header for downstream purposes, we can update test script to strip the line out (since it includes the output directory which is randomly generated at test run time).
> Resolves travis fails

- umi_tools/umi_tools.py
Also:
- minor refactor
- pass return value from command through to sys.exit()
- pretty error if the command is not known
(Didn't test this PR myself yet, just trying to fix my "first launch" experience of getting a stack trace)
> Fix "umi_tools command" prints stack trace

- umi_tools/sam_methods.py
Fixes #539.
When `TwoPassPairWriter` reaches the end of a contig, it calls `write_mates`, which reopens that contig from the start and scans through for remaining mates. To do this, `write_mates` uses `pysam.AlignmentFile.fetch(...., multiple_iterators=True)`. As the file uses is the same filehandle being used by `bundle_iterator`, then `multiple_iterators=True` ensures that the position in the file is not lost in this operation. 
`multiple_iterators=True` imposes some overhead. With a reasonable number of contigs this is not a problem, as the overhead is small compared to the cost of the scan. However, when alignment is done to the transcriptome, `write_mates` is called 100s of thousands of times, and for some reason, `fetch` calls the `__init__` of `psyam.RowIteratorRegion` 4 times for …
> Speed up writing mates

- tests/test_umi_tools.py
Changes to `pyyaml` mean that `yaml.load()` has been replaced with `yaml.safe_load()` and `yaml.full_load()`. Since we are only loading text from the testing configuration, I have replaced `yaml.load()` with `yaml.safe_load`
> Fix test_umi_tools.py

- tests/count_help
- tests/count_tab_help
- tests/dedup_help
- tests/dedup_help.txt
- tests/extract_help
- tests/group_help
- tests/tests.yaml
- tests/umi_tools_help
- tests/whitelist_help
- umi_tools/umi_tools.py
remove regression that caused umi_tools.py to quit before calling the command if --help was specified.
Added a test to test that there is help output from dedup. The reference will include the version number, which means this test will go out of date every time there is a version bump. On the other hand, should we test the help message from all tools?
> Fix lack of help messages in 1.1.4

- tests/count_help
- tests/dedup_help
- tests/group_help
- umi_tools/Utilities.py
- umi_tools/count.py
- umi_tools/dedup.py
- umi_tools/group.py
Clarifies documentation of options for chimeric read pairs, unpaired read pairs and unmapped read pairs. See #572 for details
> Improve docs re chimeric/unmapped/unpaired read pairs

- umi_tools/whitelist_methods.py
When using the UMI-tools API only, I noticed it switches my Matplotlib backend to Agg, which messes with the plots I generate downstream. This PR changes the backend only when generating plots and then switches back to the user's original setting
> change back to original matplotlib backend

- .github/workflows/python-publish-test.yml
- .github/workflows/python-publish.yml
- .github/workflows/tests.yml
This GitHub workflow will push new GH releases automatically to pypi. One caveat is that the pypi API key needs to be stored in the repository or organisation secrets (under Settings) as `PYPI_API_TOKEN`. 
Relates to issue #663
> Add workflow to push releases to pypi
